#import "../../graphql-specs/adaptcommerce.gql"

type Query implements CatalogQueries & CartQueries {
  category(id: Int!): Category
  product(sku: String!): Product
  cart: Cart
}

type Mutation implements CartMutations {
  addItemToCart(sku: String!): CartPayload
  removeItemFromCart(item_id: Int!): CartPayload
}

type FakeCart implements Cart {
  id: Int
  items_qty: Int
  items: [CartItem]
  totals: CartTotals
}

type FakeCartItem implements CartItem {
  name: String
  qty: Int
  item_id: Int
  sku: String
  product: Product
  priceInfo: CartItemPriceInfo
}

type FakeCartItemPriceInfo implements CartItemPriceInfo {
  rowTotalInclTax: Price
}

type FakeCartTotals implements CartTotals {
  subtotalInclTax: Price
}

type FakeCategory implements Category {
  name: String
  layer(params: QueryInput!): Layer
}

type FakeLayer implements Layer {
  products: [Product]
}

type FakeProduct implements Product {
  sku: String
  name: String
  description: String
  imageUrl: String
  prices: ProductPrices
}

type FakeProductPrices implements ProductPrices {
  finalPrice: BothInclAndExclTaxesPrice
}
